### ISSUE TITLE
Some bugs about the code

### ISSUE THREAD

**Issue by leehyunseo03** [dastyinc/loq0#1]
1. The turn does not change when player put a wall
2. state.act() returns None even though the action is valid
3. the move action still break through the wall

**Comment by leehyunseo03** [comment]
I made a pretty simple gameplay code and found bug with this. please check mymcts.h repository, branch : bugs/gameplay

**Comment by seo-rii** [comment]
1. Fixed.
2. In your code, you are using Game object. Game.act does not returns State if act is valid. Instead, it returns True. Please refer to play.py.
3. Will be fixed soon.

**Comment by seo-rii** [comment]
Fixed!
