### ISSUE TITLE
Bug that a wall can be overlapped with other wall

### ISSUE THREAD

**Issue by idearendil** [dastyinc/loq0#3]
In the test code,

I 8 7 2
I 9 5 1
I 7 7 2

this sequence of actions results in a bug that a wall is overlapped with other wall.

**Comment by idearendil** [comment]
I don't know it's related, but there is another similar bug.
In the test code,

I 8 7 2
I 8 5 1
I 8 6 2

this sequence of actions returns None even if it has not violated any rule, as far as I know.

**Comment by seo-rii** [comment]
Fixed on 0.0.10
