### ISSUE TITLE
Bug around border issue

### ISSUE THREAD

**Issue by idearendil** [dastyinc/loq0#5]
It should be allowed for a pawn to overlap with another pawn when it enters the bush zone,
not only when it's completely in the bush zone, according to the game proposal.

Specifically, refer to this example:

M 5 2
M 5 8
M 5 3
M 5 7
M 5 4
M 6 7
M 5 5
M 5 7
M 5 6
M 5 6

It returns None when the red pawn tries to enter the bush. I guess it should be allowed too.

**Comment by seo-rii** [comment]
Fixed on 0.0.11.
