### ISSUE TITLE
Problem with 'face to face' situation

### ISSUE THREAD

**Issue by idearendil** [dastyinc/loq0#7]
There is an corner case where a pawn is at the edge of the board and another pawn is right next to it.

Please refer to this play sequence at the test code.
M 4 1
M 4 9
M 3 1
M 3 9
M 2 1
M 2 9
M 1 1
M 2 8
M 1 2
M 2 7
M 1 3
M 2 6
M 1 4
M 2 5
M 1 5
M 1 4 - Here, game returns None.

According to this web page,
https://boardgames.stackexchange.com/questions/57109/quoridor-jumps-at-the-edge-of-the-board
it should be allowed for the pawn to jump on to one of the two cells.
I'd be happy if it's corrected after the C porting completed😊😊

**Comment by seo-rii** [comment]
Fixed on loq2.
