### ISSUE TITLE
When a minor invalid action comes in

### ISSUE THREAD

**Issue by idearendil** [dastyinc/loq0#8]
There's some circumstances where an agent breaks some rule but the environment just skips its turn, not making it lose.
Such as below circumstance.

M 5 2
M 5 8
M 5 3
M 5 7
M 5 4
M 5 6
I 2 6 2
I 4 6 2
I 6 6 2
I 8 6 2
L 1 6 1

It should skip the agent's turn, but it remains its turn.
According to the game design proposal, it should be changed to its opponent's turn.

**Comment by seo-rii** [comment]
Fixed on loq2.
